pipeline{
   agent any
   tools{
   maven 'M2_HOME'
   }
   stages{
    stage("maven config steps"){
        steps{
        sh 'mvn clean validate compile install test '
        }
    }
    stage('Packaging'){
        steps{
        sh 'mvn package'
        }
    }
   
   }
}