pipeline{
   agent any
   tools{
   maven 'M2_HOME'
   }
   stages{
   stage('sonar scan for vurnalabilities'){
    steps{
    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gad0788_geo'
    }
   }
    stage("maven config steps"){
        steps{
        sh 'mvn clean validate compile install test '
        }
    }
    stage('Packaging'){
        steps{
        sh 'mvn package'
        }
    }
    stage('Uploading artifacts to Jfrog'){
        steps{
        sh 'curl -uadmin:APAXDsGHWiYuC6jXqEFR2f9khMP -T target/bio*.jar\
        "http://ec2-54-89-89-62.compute-1.amazonaws.com:8081/artifactory/geolocation_1/geoapp/bio_${BUILD_ID}.jar"'
        }
    }
    
   
   }
}